spring.application.name=RateLimiter
spring.datasource.url=jdbc:mysql://localhost:3306/rate_limiter_db
spring.datasource.username=root
spring.datasource.password=Naman9893#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=sj3h1dSAGJfQfhgxJaPNNSUS8afmyey0uwm51JHlMAo
jwt.expiration=3600000